# Generated by Django 5.2.7 on 2025-12-04 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profesor",
            options={
                "ordering": ["apellido", "-nombre"],
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="profesor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="entidades.profesor",
            ),
        ),
    ]
